### PR TITLE
 CentOS 7.1 add cloud repos that has included openstack-kilo

### PR DESCRIPTION
**Pull request by barrowkwan**
CentOS 7 .1 added cloud repo that has included openstack-kilo

### CODE REVIEW

**Comment by barrowkwan** [comment]
It has 6 ( since 6.6, thus 6.5 and early doesn't have it ).  not for 5 neither.

I will push another changes soon as I just found out there is a dedicated Cloud key.

**Comment by someara** [comment]
Thanks Barrow

**Comment by Sauraus** [comment]
I would also suggest make the inclusion conditional on 7.1 and also extend the server spec test to include this.

**Comment by barrowkwan** [comment]
Hi,
	I am going to cancel my pull request for now.  I just find out the http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=cloud <http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=cloud>  didn’t provide valid URL like the other repo ( e.g. os, updates, extras contrib, etc… ).  I will find out more and support a new pull request

thanks!

Barrow

**Comment by someara** [comment]
Okay I'll keep an eye out

**Pull request closed without merging**
