### PR TITLE
releasever requires centos-release pkg, removing this dependency.

### PR DESCRIPTION
**Pull request by chasebolt**

### CODE REVIEW

**Comment by ramereth** [comment]
@chasebolt I'm looking at reverting this change in #35, however it was brought to my attention that there might have been a reason for doing this and I noticed this PR. I'm having a hard time understanding why you would run a CentOS system without centos-release installed. Can you please elaborate more on the use case? Thanks!

**Comment by chasebolt** [comment]
my only guess is it was 2017 and centos images werent perfect everywhere. using chef made it work 100% no matter the case. example is issue #10.

**Comment by ramereth** [comment]
@chasebolt for issue #10, the file will never actually translate the ``$releasever``, however the system will do that internally. I'd like to try and see how this affects people and can revert it later if it becomes a problem. This is how upstream does this so it should work. Thanks for the feedback!

**Comment by chasebolt** [comment]
iirc if a user doesnt have `centos-release` installed (they should obv, but not always the case with people making super slim kickstarted images), then yum will not internally replace it.

**Pull request merged**
